MoC/settings.py, comments/admin.py, comments/apps.py, comments/models.py, comments/serializers/comments_serializers.py, comments/tests.py, comments/views.py, posts/admin.py, posts/apps.py, posts/models.py, posts/serializers/posts_serializers.py, posts/tests.py, posts/views.py
- post, comment 모델 작성
- post, comment serializer 작성
=> feat: post, comment 모델 작성

MoC/urls.py, comments/admin.py, comments/models.py, comments/urls.py, posts/admin.py, posts/models.py, posts/urls.py, posts/views.py
- 게시물 기본 CRUD 작성
- api 명세서 업데이트 완료 (노션)
---
- 피그마에 카테고리 부분이 별도로 없어서 카테고리 모델 부분 삭제했습니다
=> feat: 게시물 CRUD

MoC/settings.py, accounts/models.py, accounts/serializers/user_serializers.py, accounts/urls.py, accounts/views/__init__.py, accounts/views/auth_user_views.py, accounts/views/my_page_views.py, accounts/views/user_info_views.py, category/admin.py, category/apps.py, category/models/__init__.py, category/models/category_models.py, category/tests.py, comments/admin.py, comments/models.py, comments/serializers/comments_serializers.py, posts/admin.py, posts/models.py, posts/serializers/posts_serializers.py, utils/image_compressor.py
- 모델 일부 수정 및 시리얼라이저 생성
- 이미지 컴프레서 객체화
=> [FEAT] 모델 일부 수정 및 시리얼라이저 생성

posts/views/post_CRUD_views.py
=> feat: 게시글 생성 뷰 추가

accounts/urls.py
=> fix: url 추가

accounts/views/auth_dev_views.py
=> refactor: 로컬 로그인 분리

accounts/views/auth_dev_views.py
=> feat: 로그인 분리

accounts/views/auth_dev_views.py
=> refactor: redirect uri 수정

accounts/views/auth_user_views.py
=> remove: referer

accounts/urls.py, accounts/views/auth_user_views.py
=> refactor: code 파라미터로 수정

accounts/views/auth_user_views.py
=> feat: 유저 정보 출력

accounts/views/auth_user_views.py
=> feat: 카카오 로그인 완성

accounts/views/auth_dev_views.py
=> refactor: 로그인 url 통합

MoC/settings.py
=> chore: 액세스 토큰 유효기간 조정

accounts/urls.py, accounts/views/auth_dev_views.py
=> feat: 개발자 서버 로그인 뷰 추가

MoC/settings.py
=> chore: CORS, CSRF 추가

posts/models.py, posts/serializers/posts_serializers.py, posts/urls.py, posts/views/__init__.py, posts/views/post_CRUD_views.py, posts/views/post_list_views.py
=> feat: 게시글 리스트 뷰 추가

comments/serializers/comments_serializers.py, comments/urls.py, comments/views.py
=> feat: 댓글 기능 구현

daily/admin.py
=> feat: 기간 모델 어드민 페이지 등록

docker-compose.yml
=> fix: crontab 명령어 수정

comments/views.py
- response body > post serializer로 수정
=> fix: post serializer로 수정

posts/serializers/posts_serializers.py, posts/urls.py, posts/views/post_list_views.py
=> feat: 문장/해시태그로 게시글 검색 뷰 추가

posts/admin.py
=> feat: 게시글 이미지 어드민 페이지 추가

MoC/settings.py
=> chore: 액세스 토큰 수명 수정

daily/cron.py, daily/views/popular_post_views.py
=> fix: 로컬 시각 적용

daily/views/test_views.py
=> fix: 인기글 썸네일 수정

posts/views/post_list_views.py
=> feat: 전체 최신글 추가

comments/models.py, comments/views.py, posts/serializers/posts_serializers.py
=> fix: parent 삭제

posts/serializers/posts_serializers.py
=> feat: 게시글 리스트에 좋아요, 댓글 개수 추가
